auth with jwt
tmpbook/GC4K pull request #4
Opened 2020-01-09 13:44 UTC by aguncn

使用controller , service , model三层，
实现使用json web token的认证，
并将其加入中间件。

2020-01-10 16:12 UTC, tmpbook requested changes

2020-01-10 16:12 UTC, tmpbook commented on controllers/auth.go
> +	c.JSON(http.StatusOK, gin.H{
https://github.com/tmpbook/GC4K/blob/master/controllers/ci.go#L12
gin.H 本身只是一个 map[string]interface 类型，没有固定的格式，这样容易返回给前端的格式不固定，或者敲错单词，最好用我上面链接的那个 type

2020-01-10 16:12 UTC, tmpbook commented on models/app.go
> +// App组件模型
首字母大写的结构体或者方法都是可以开放到此包外边区使用的，
注释格式是：
`//[空格]名字[空格]注释`

2020-01-10 16:12 UTC, tmpbook commented on models/init.go
> -	dbDriver, err := cfg.GetValue("db-dev", "db_driver")
推荐使用驼峰命名

2020-01-10 16:12 UTC, tmpbook commented on router/router.go
> +	apiAuthorized.Use(middlewares.UserAuth(), middlewares.APIAuth())
中间件会按顺序执行，和 Django 类似，不过好像只有请求进来有用，和 Django 的洋葱模型不同
UserAuth 和 APIAuth 我之前想的是给不同路由用的，有的路由提供给 API 访问，有个路由提供给用户使用

2020-01-12 03:23 UTC, aguncn commented
收到，我在下一版，改进一下哈，再来提交 。

2020-01-12 03:23 UTC, closed without merging